// auto generated with extractor.js
import type { Things } from "./types";

const species: Things = {
  species_cat: { name: "Cat", category: "species", icon: "cosmetic_icons3.png" },
  species_dog: { name: "Dog", category: "species", icon: "cosmetic_icons2.png" }
};

const accessory: Things = {
  accessory_alien_particles: { name: "Alien Particles", category: "accessory", icon: "cosmetic_icons43.png" },
  accessory_antlers: { name: "Antlers", category: "accessory", icon: "cosmetic_icons63.png" },
  accessory_bandaid: { name: "Bandage", category: "accessory", icon: "cosmetic_icons33.png" },
  accessory_cig: { name: "Cigarette", category: "accessory", icon: "cosmetic_icons36.png" },
  accessory_collar: { name: "Collar", category: "accessory", icon: "cosmetic_icons28.png" },
  accessory_collar_bell: { name: "Belled Collar", category: "accessory", icon: "cosmetic_icons29.png" },
  accessory_eyepatch: { name: "Eyepatch", category: "accessory", icon: "cosmetic_icons30.png" },
  accessory_glasses: { name: "Glasses", category: "accessory", icon: "cosmetic_icons7.png" },
  accessory_glasses_round: { name: "Round Glasses", category: "accessory", icon: "cosmetic_icons38.png" },
  accessory_gloves_black: { name: "Black Gloves", category: "accessory", icon: "cosmetic_icons1.png" },
  accessory_goldsparkle_particles: {
    name: "Gold Sparkle Particles",
    category: "accessory",
    icon: "cosmetic_icons42.png"
  },
  accessory_heart_particles: { name: "Heart Particles", category: "accessory", icon: "cosmetic_icons39.png" },
  accessory_hook: { name: "Hook Hand", category: "accessory", icon: "cosmetic_icons37.png" },
  accessory_monocle: { name: "Gold Monocle", category: "accessory", icon: "cosmetic_icons15.png" },
  accessory_rain_boots_green: { name: "Green Rain Boots", category: "accessory", icon: "cosmetic_icons31.png" },
  accessory_rain_boots_yellow: { name: "Yellow Rain Boots", category: "accessory", icon: "cosmetic_icons31.png" },
  accessory_ring: { name: "Diamond Ring", category: "accessory", icon: "cosmetic_icons65.png" },
  accessory_shades: { name: "Shades", category: "accessory", icon: "cosmetic_icons8.png" },
  accessory_shades_gold: { name: "Golden Shades", category: "accessory", icon: "cosmetic_icons8.png" },
  accessory_shoes: { name: "Shoes", category: "accessory", icon: "cosmetic_icons31.png" },
  accessory_sparkle_particles: { name: "Sparkle Particles", category: "accessory", icon: "cosmetic_icons41.png" },
  accessory_stink_particles: { name: "Smelly Particles", category: "accessory", icon: "cosmetic_icons40.png" },
  accessory_sword: { name: "Sword", category: "accessory", icon: "cosmetic_icons16.png" },
  accessory_watch: { name: "Gold Watch", category: "accessory", icon: "cosmetic_icons14.png" }
};

const bobber: Things = {
  bobber_bomb: { name: "Bomb Bobber", category: "bobber", icon: "cosmetic_icons48.png" },
  bobber_default: { name: "Red Bobber", category: "bobber", icon: "cosmetic_icons6.png" },
  bobber_ducky: { name: "Ducky Bobber", category: "bobber", icon: "cosmetic_icons46.png" },
  bobber_lilypad: { name: "Lilypad Bobber", category: "bobber", icon: "cosmetic_icons47.png" },
  bobber_slip: { name: "Slip Bobber", category: "bobber", icon: "cosmetic_icons45.png" }
};

const eye: Things = {
  eye_alien: { name: "Alien", category: "eye", icon: "box_eye1.png" },
  eye_almond: { name: "Almond", category: "eye", icon: "apple_eye4.png" },
  eye_angry: { name: "Angry", category: "eye", icon: "eyes_base8.png" },
  eye_annoyed: { name: "Annoyed", category: "eye", icon: "fuzz_eye4.png" },
  eye_bagged: { name: "Bagged", category: "eye", icon: "eyes_base23.png" },
  eye_catsoup: { name: "Catsoup", category: "eye", icon: "roaway_eye5.png" },
  eye_closed: { name: "Closed", category: "eye", icon: "eyes_base4.png" },
  eye_dispondant: { name: "Dispondant", category: "eye", icon: "roaway_eye6.png" },
  eye_distraught: { name: "Distraught", category: "eye", icon: "fuzz_eye7.png" },
  eye_dot: { name: "Dot", category: "eye", icon: "eyes_base12.png" },
  eye_drained: { name: "Drained", category: "eye", icon: "box_eye3.png" },
  eye_dreaming: { name: "Dreaming", category: "eye", icon: "apple_eye5.png" },
  eye_fierce: { name: "Fierce", category: "eye", icon: "apple_eye2.png" },
  eye_focused: { name: "Focused", category: "eye", icon: "box_eye2.png" },
  eye_froggy: { name: "Froggy", category: "eye", icon: "fuzz_eye6.png" },
  eye_glamor: { name: "Glamor", category: "eye", icon: "fuzz_eye5.png" },
  eye_glance: { name: "Glance", category: "eye", icon: "box_eye5.png" },
  eye_glare: { name: "Glare", category: "eye", icon: "fuzz_eye3.png" },
  eye_goat: { name: "Goat", category: "eye", icon: "roaway_eye1.png" },
  eye_halfclosed: { name: "Sleepy", category: "eye", icon: "eyes_base1.png" },
  eye_harper: { name: "Harper", category: "eye", icon: "apple_eye1.png" },
  eye_haunted: { name: "Haunted", category: "eye", icon: "fuzz_eye2.png" },
  eye_herbal: { name: "Herbal", category: "eye", icon: "eyes_base22.png" },
  eye_inverted: { name: "Inverted", category: "eye", icon: "roaway_eye2.png" },
  eye_jolly: { name: "Jolly", category: "eye", icon: "box_eye4.png" },
  eye_lenny: { name: "Lenny", category: "eye", icon: "apple_eye3.png" },
  eye_plead: { name: "Pleading", category: "eye", icon: "eyes_base6.png" },
  eye_possessed: { name: "Possessed", category: "eye", icon: "fuzz_eye8.png" },
  eye_sad: { name: "Sad", category: "eye", icon: "eyes_base7.png" },
  eye_sassy: { name: "Sassy", category: "eye", icon: "fuzz_eye1.png" },
  eye_scribble: { name: "Scribble", category: "eye", icon: "box_eye6.png" },
  eye_serious: { name: "Serious", category: "eye", icon: "eyes_base15.png" },
  eye_sideeye: { name: "Side Eye", category: "eye", icon: "eyes_base11.png" },
  eye_spiral: { name: "Spiral", category: "eye", icon: "eyes_base3.png" },
  eye_squared: { name: "Squared", category: "eye", icon: "roaway_eye3.png" },
  eye_starlight: { name: "Starlight", category: "eye", icon: "roaway_eye4.png" },
  eye_tired: { name: "Tired", category: "eye", icon: "eyes_base14.png" },
  eye_wings: { name: "Wings", category: "eye", icon: "apple_eye6.png" },
  eye_x: { name: "X", category: "eye", icon: "eyes_base13.png" }
};

const hat: Things = {
  hat_baseball_cap_big: { name: "Fear Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_green: { name: "Fish Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_mcd: { name: "Fastfood Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_missing: { name: "Missing Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_orange: { name: "Catfish Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_pee: { name: "Peeing Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_size: { name: "Size Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_baseball_cap_sports: { name: "Sport Baseball Cap", category: "hat", icon: "cosmetic_icons34.png" },
  hat_beanie_black: { name: "Black Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_beanie_blue: { name: "Blue Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_beanie_green: { name: "Green Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_beanie_maroon: { name: "Maroon Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_beanie_teal: { name: "Teal Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_beanie_white: { name: "White Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_beanie_yellow: { name: "Yellow Beanie", category: "hat", icon: "cosmetic_icons35.png" },
  hat_bucket_green: { name: "Green Bucket Hat", category: "hat", icon: "cosmetic_icons25.png" },
  hat_bucket_tan: { name: "Tan Bucket Hat", category: "hat", icon: "cosmetic_icons25.png" },
  hat_cowboyhat_black: { name: "Black Cowboy Hat", category: "hat", icon: "cosmetic_icons27.png" },
  hat_cowboyhat_brown: { name: "Brown Cowboy Hat", category: "hat", icon: "cosmetic_icons27.png" },
  hat_cowboyhat_pink: { name: "Pink Cowboy Hat", category: "hat", icon: "cosmetic_icons27.png" },
  hat_crown: { name: "Crown", category: "hat", icon: "cosmetic_icons26.png" },
  hat_tophat: { name: "Top Hat", category: "hat", icon: "cosmetic_icons13.png" }
};

const legs: Things = {
  legs_pants_long_black: { name: "Black Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_blue: { name: "Blue Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_brown: { name: "Brown Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_green: { name: "Green Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_grey: { name: "Grey Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_maroon: { name: "Maroon Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_olive: { name: "Olive Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_orange: { name: "Orange Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_purple: { name: "Purple Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_red: { name: "Red Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_salmon: { name: "Salmon Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_tan: { name: "Tan Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_teal: { name: "Teal Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_white: { name: "White Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_long_yellow: { name: "Yellow Pants", category: "legs", icon: "cosmetic_icons11.png" },
  legs_pants_short_black: { name: "Black Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_blue: { name: "Blue Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_brown: { name: "Brown Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_green: { name: "Green Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_grey: { name: "Grey Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_maroon: { name: "Maroon Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_olive: { name: "Olive Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_orange: { name: "Orange Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_purple: { name: "Purple Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_red: { name: "Red Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_salmon: { name: "Salmon Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_tan: { name: "Tan Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_teal: { name: "Teal Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_white: { name: "White Shorts", category: "legs", icon: "cosmetic_icons12.png" },
  legs_pants_short_yellow: { name: "Yellow Shorts", category: "legs", icon: "cosmetic_icons12.png" }
};

const mouth: Things = {
  mouth_aloof: { name: "Aloof", category: "mouth", icon: "mouth_base7.png" },
  mouth_animal: { name: "Animal", category: "mouth", icon: "mouth_base8.png" },
  mouth_bite: { name: "Bite", category: "mouth", icon: "roaway_mouth3.png" },
  mouth_braces: { name: "Braces", category: "mouth", icon: "roaway_mouth1.png" },
  mouth_bucktoothed: { name: "Bucktoothed", category: "mouth", icon: "mouth_base13.png" },
  mouth_chewing: { name: "Chewing", category: "mouth", icon: "mouth_base16.png" },
  mouth_dead: { name: "Dead", category: "mouth", icon: "mouth_base18.png" },
  mouth_default: { name: ":3", category: "mouth", icon: "mouth_base1.png" },
  mouth_distraught: { name: "Distraught", category: "mouth", icon: "mouth_base12.png" },
  mouth_drool: { name: "Drool", category: "mouth", icon: "roaway_mouth4.png" },
  mouth_fangs: { name: "Fangs", category: "mouth", icon: "roaway_mouth2.png" },
  mouth_fishy: { name: "Fishy", category: "mouth", icon: "roaway_mouth5.png" },
  mouth_glad: { name: "Glad", category: "mouth", icon: "mouth_base22.png" },
  mouth_grimace: { name: "Grimace", category: "mouth", icon: "mouth_base23.png" },
  mouth_grin: { name: "Grin", category: "mouth", icon: "mouth_base10.png" },
  mouth_happy: { name: "Happy", category: "mouth", icon: "mouth_base11.png" },
  mouth_hymn: { name: "Hymn", category: "mouth", icon: "mouth_base26.png" },
  mouth_jaws: { name: "Jaws", category: "mouth", icon: "apple_mouth1.png" },
  mouth_monster: { name: "Monster", category: "mouth", icon: "box_mouth1.png" },
  mouth_none: { name: "No Mouth", category: "mouth", icon: "mouth_base15.png" },
  mouth_rabid: { name: "Rabid", category: "mouth", icon: "mouth_base27.png" },
  mouth_sabertooth: { name: "Sabertooth", category: "mouth", icon: "mouth_base25.png" },
  mouth_shocked: { name: "Shocked", category: "mouth", icon: "mouth_base19.png" },
  mouth_smirk: { name: "Smirk", category: "mouth", icon: "mouth_base17.png" },
  mouth_squiggle: { name: "Squiggle", category: "mouth", icon: "mouth_base21.png" },
  mouth_stitch: { name: "Stitch", category: "mouth", icon: "box_mouth2.png" },
  mouth_tongue: { name: "Tongue", category: "mouth", icon: "mouth_base9.png" },
  mouth_toothier: { name: "Toothier", category: "mouth", icon: "mouth_base24.png" },
  mouth_toothy: { name: "Toothy", category: "mouth", icon: "mouth_base4.png" }
};

const nose: Things = {
  nose_booger: { name: "Booger", category: "nose", icon: "nose8.png" },
  nose_button: { name: "Button", category: "nose", icon: "nose6.png" },
  nose_cat: { name: "Cat", category: "nose", icon: "nose2.png" },
  nose_clown: { name: "Clown", category: "nose", icon: "roaway_nose1.png" },
  nose_dog: { name: "Dog", category: "nose", icon: "nose3.png" },
  nose_long: { name: "Long", category: "nose", icon: "nose12.png" },
  nose_none: { name: "No Nose", category: "nose", icon: "nose1.png" },
  nose_nostril: { name: "Nostril", category: "nose", icon: "nose11.png" },
  nose_pierced: { name: "Pierced", category: "nose", icon: "nose5.png" },
  nose_pink: { name: "Pink", category: "nose", icon: "nose10.png" },
  nose_round: { name: "Round", category: "nose", icon: "nose4.png" },
  nose_v: { name: "V", category: "nose", icon: "nose7.png" },
  nose_whisker: { name: "Whiskers", category: "nose", icon: "nose9.png" }
};

const overshirt: Things = {
  overshirt_flannel_closed_black: {
    name: "Black Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_closed_blue: { name: "Blue Flannel (Closed)", category: "overshirt", icon: "cosmetic_icons10.png" },
  overshirt_flannel_closed_green: {
    name: "Green Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_closed_olive: {
    name: "Olive Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_closed_purple: {
    name: "Purple Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_closed_red: { name: "Red Flannel (Closed)", category: "overshirt", icon: "cosmetic_icons10.png" },
  overshirt_flannel_closed_salmon: {
    name: "Salmon Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_closed_teal: { name: "Teal Flannel (Closed)", category: "overshirt", icon: "cosmetic_icons10.png" },
  overshirt_flannel_closed_white: {
    name: "White Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_closed_yellow: {
    name: "Yellow Flannel (Closed)",
    category: "overshirt",
    icon: "cosmetic_icons10.png"
  },
  overshirt_flannel_open_black: { name: "Black Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_blue: { name: "Blue Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_green: { name: "Green Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_olive: { name: "Olive Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_purple: { name: "Purple Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_red: { name: "Red Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_salmon: { name: "Salmon Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_teal: { name: "Teal Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_white: { name: "White Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_flannel_open_yellow: { name: "Yellow Flannel (Open)", category: "overshirt", icon: "cosmetic_icons9.png" },
  overshirt_labcoat: { name: "Labcoat", category: "overshirt", icon: "cosmetic_icons66.png" },
  overshirt_overall_brown: { name: "Brown Overalls", category: "overshirt", icon: "cosmetic_icons24.png" },
  overshirt_overall_green: { name: "Green Overalls", category: "overshirt", icon: "cosmetic_icons24.png" },
  overshirt_overall_grey: { name: "Grey Overalls", category: "overshirt", icon: "cosmetic_icons24.png" },
  overshirt_overall_olive: { name: "Olive Overalls", category: "overshirt", icon: "cosmetic_icons24.png" },
  overshirt_overall_tan: { name: "Tan Overalls", category: "overshirt", icon: "cosmetic_icons24.png" },
  overshirt_overall_yellow: { name: "Yellow Overalls", category: "overshirt", icon: "cosmetic_icons24.png" },
  overshirt_sweatshirt_black: { name: "Black Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_blue: { name: "Blue Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_brown: { name: "Brown Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_green: { name: "Green Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_grey: { name: "Grey Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_maroon: { name: "Maroon Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_olive: { name: "Olive Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_orange: { name: "Orange Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_purple: { name: "Purple Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_red: { name: "Red Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_salmon: { name: "Salmon Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_tan: { name: "Tan Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_teal: { name: "Teal Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_white: { name: "White Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_sweatshirt_yellow: { name: "Yellow Hoodie", category: "overshirt", icon: "cosmetic_icons18.png" },
  overshirt_trenchcoat: { name: "Trenchcoat", category: "overshirt", icon: "cosmetic_icons66.png" },
  overshirt_vest_black: { name: "Black Vest", category: "overshirt", icon: "cosmetic_icons19.png" },
  overshirt_vest_green: { name: "Green Vest", category: "overshirt", icon: "cosmetic_icons19.png" },
  overshirt_vest_grey: { name: "Grey Vest", category: "overshirt", icon: "cosmetic_icons19.png" },
  overshirt_vest_olive: { name: "Olive Vest", category: "overshirt", icon: "cosmetic_icons19.png" },
  overshirt_vest_tan: { name: "Tan Vest", category: "overshirt", icon: "cosmetic_icons19.png" }
};

const pattern: Things = {
  pattern_calico: { name: "Calico Pattern", category: "pattern", icon: "cosmetic_icons61.png" },
  pattern_collie: { name: "Collie Pattern", category: "pattern", icon: "cosmetic_icons61.png" },
  pattern_spotted: { name: "Spotted Pattern", category: "pattern", icon: "cosmetic_icons61.png" },
  pattern_tux: { name: "Tux Pattern", category: "pattern", icon: "cosmetic_icons61.png" }
};

const primary_color: Things = {
  pcolor_black: { name: "Black Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_blue: { name: "Blue Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_brown: { name: "Brown Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_green: { name: "Green Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_grey: { name: "Grey Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_maroon: { name: "Maroon Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_midnight_special: { name: "Midnight Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_olive: { name: "Olive Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_orange: { name: "Orange Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_pink_special: { name: "Pink Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_purple: { name: "Purple Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_red: { name: "Red Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_salmon: { name: "Salmon Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_stone_special: { name: "Stone Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_tan: { name: "Tan Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_teal: { name: "Teal Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_west: { name: "West Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_white: { name: "White Fur", category: "primary_color", icon: "cosmetic_icons4.png" },
  pcolor_yellow: { name: "Yellow Fur", category: "primary_color", icon: "cosmetic_icons4.png" }
};

const secondary_color: Things = {
  scolor_black: { name: "Black Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_blue: { name: "Blue Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_brown: { name: "Brown Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_green: { name: "Green Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_grey: { name: "Grey Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_maroon: { name: "Maroon Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_midnight_special: { name: "Midnight Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_olive: { name: "Olive Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_orange: { name: "Orange Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_pink_special: { name: "Pink Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_purple: { name: "Purple Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_red: { name: "Red Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_salmon: { name: "Salmon Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_stone_special: { name: "Stone Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_tan: { name: "Tan Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_teal: { name: "Teal Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_white: { name: "White Fur", category: "secondary_color", icon: "cosmetic_icons4.png" },
  scolor_yellow: { name: "Yellow Fur", category: "secondary_color", icon: "cosmetic_icons4.png" }
};

const tail: Things = {
  tail_cat: { name: "Cat Tail", category: "tail", icon: "cosmetic_icons5.png" },
  tail_dog_fluffy: { name: "Fluffy Tail", category: "tail", icon: "cosmetic_icons21.png" },
  tail_dog_short: { name: "Short Tail", category: "tail", icon: "cosmetic_icons23.png" },
  tail_dog_thin: { name: "Dog Tail", category: "tail", icon: "cosmetic_icons20.png" },
  tail_fox: { name: "Fox Tail", category: "tail", icon: "cosmetic_icons22.png" }
};

const title: Things = {
  title_ace: { name: "Ace Title", category: "title", icon: "cosmetic_icons62.png" },
  title_ancient: { name: "Ancient Title", category: "title", icon: "cosmetic_icons62.png" },
  title_bi: { name: "Bi Title", category: "title", icon: "cosmetic_icons62.png" },
  title_bipedalanimaldrawer: { name: "Bipedal Animal Drawer Title", category: "title", icon: "cosmetic_icons62.png" },
  title_catfisher: { name: "Catfisher Title", category: "title", icon: "cosmetic_icons62.png" },
  title_cozy: { name: "Cozy Title", category: "title", icon: "cosmetic_icons62.png" },
  title_critter: { name: "Critter Title", category: "title", icon: "cosmetic_icons62.png" },
  title_dude: { name: "Dude Title", category: "title", icon: "cosmetic_icons62.png" },
  title_elite: { name: "Elite Title", category: "title", icon: "cosmetic_icons62.png" },
  title_equalsthree: { name: ":3 Title", category: "title", icon: "cosmetic_icons62.png" },
  title_fishpilled: { name: "Fish-Pilled Title", category: "title", icon: "cosmetic_icons62.png" },
  title_gay: { name: "Gay Title", category: "title", icon: "cosmetic_icons62.png" },
  title_goldenbass: {
    name: "The Title Only For People Who Caught The Super Duper Rare Golden Bass Title",
    category: "title",
    icon: "cosmetic_icons62.png"
  },
  title_goldenray: {
    name: "The Title Only For People Who Caught The Super Duper Rare Golden Ray Title",
    category: "title",
    icon: "cosmetic_icons62.png"
  },
  title_goober: { name: "Goober Title", category: "title", icon: "cosmetic_icons62.png" },
  title_goodboy: { name: "Good Boy Title", category: "title", icon: "cosmetic_icons62.png" },
  title_goodgirl: { name: "Good Girl Title", category: "title", icon: "cosmetic_icons62.png" },
  title_imnormal: { name: "Normal and Regular Title", category: "title", icon: "cosmetic_icons62.png" },
  title_iscool: { name: "Is Cool Title", category: "title", icon: "cosmetic_icons62.png" },
  title_king: { name: "King Title", category: "title", icon: "cosmetic_icons62.png" },
  title_kitten: { name: "Kitten Title", category: "title", icon: "cosmetic_icons62.png" },
  title_koiboy: { name: "Koi Boy Title", category: "title", icon: "cosmetic_icons62.png" },
  title_lamedev: { name: "Fake Lamedev Title", category: "title", icon: "cosmetic_icons62.png" },
  title_lamedev_real: { name: "Lamedev Title", category: "title", icon: "cosmetic_icons62.png" },
  title_lesbian: { name: "Lesbian Title", category: "title", icon: "cosmetic_icons62.png" },
  title_littlelad: { name: "Little Lad Title", category: "title", icon: "cosmetic_icons62.png" },
  title_majestic: { name: "Majestic Title", category: "title", icon: "cosmetic_icons62.png" },
  title_musky: { name: "Musky Title", category: "title", icon: "cosmetic_icons62.png" },
  title_nightcrawler: { name: "Night Crawler Title", category: "title", icon: "cosmetic_icons62.png" },
  title_none: { name: "No Title", category: "title", icon: "cosmetic_icons62.png" },
  title_pan: { name: "Pan Title", category: "title", icon: "cosmetic_icons62.png" },
  title_pretty: { name: "Pretty Title", category: "title", icon: "cosmetic_icons62.png" },
  title_problematic: { name: "Problematic Title", category: "title", icon: "cosmetic_icons62.png" },
  title_pup: { name: "Pup Title", category: "title", icon: "cosmetic_icons62.png" },
  title_puppy: { name: "Puppy Title", category: "title", icon: "cosmetic_icons62.png" },
  title_queer: { name: "Queer Title", category: "title", icon: "cosmetic_icons62.png" },
  title_sharkbait: { name: "Shark Bait Title", category: "title", icon: "cosmetic_icons62.png" },
  title_shithead: { name: "Shithead Title", category: "title", icon: "cosmetic_icons62.png" },
  title_sillyguy: { name: "Silly Guy Title", category: "title", icon: "cosmetic_icons62.png" },
  title_soggy: { name: "Soggy Doggy Title", category: "title", icon: "cosmetic_icons62.png" },
  title_special: { name: "Special Title", category: "title", icon: "cosmetic_icons62.png" },
  title_stinkerdinker: { name: "Stinker Dinker Title", category: "title", icon: "cosmetic_icons62.png" },
  title_strongestwarrior: { name: "Strongest Warrior Title", category: "title", icon: "cosmetic_icons62.png" },
  title_stupididiotbaby: { name: "Stupid Idiot Baby Title", category: "title", icon: "cosmetic_icons62.png" },
  title_trans: { name: "Trans Title", category: "title", icon: "cosmetic_icons62.png" },
  title_yapper: { name: "Yapper Title", category: "title", icon: "cosmetic_icons62.png" }
};

const undershirt: Things = {
  undershirt_graphic_tshirt_ace: { name: "Ace T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_anchor: { name: "Anchor T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_bi: { name: "Bi T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_burger: { name: "Burger T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_dare: { name: "DARE T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_gay: { name: "Gay T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_goodboy: { name: "Good Boy T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_hooklite: {
    name: "Hook Lite T-Shirt",
    category: "undershirt",
    icon: "cosmetic_icons32.png"
  },
  undershirt_graphic_tshirt_lesbian: { name: "Lesbian T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_milf: { name: "MILF T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_mlm: { name: "Mlm T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_nobait: { name: "No Bait T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_pan: { name: "Pan T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_smokemon: {
    name: "Smoke' Mon T-Shirt",
    category: "undershirt",
    icon: "cosmetic_icons32.png"
  },
  undershirt_graphic_tshirt_soscary: { name: "So Scary T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_soup: { name: "Soup T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_graphic_tshirt_threewolves: {
    name: "Three Wolves T-Shirt",
    category: "undershirt",
    icon: "cosmetic_icons32.png"
  },
  undershirt_graphic_tshirt_trans: { name: "Trans T-Shirt", category: "undershirt", icon: "cosmetic_icons32.png" },
  undershirt_tanktop_black: { name: "Black Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_blue: { name: "Blue Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_brown: { name: "Brown Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_green: { name: "Green Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_grey: { name: "Grey Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_maroon: { name: "Maroon Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_olive: { name: "Olive Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_orange: { name: "Orange Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_purple: { name: "Purple Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_red: { name: "Red Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_salmon: { name: "Salmon Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_tan: { name: "Tan Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_teal: { name: "Teal Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_white: { name: "White Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tanktop_yellow: { name: "Yellow Tank-Top", category: "undershirt", icon: "cosmetic_icons17.png" },
  undershirt_tshirt_black: { name: "Black T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_blue: { name: "Blue T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_brown: { name: "Brown T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_green: { name: "Green T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_grey: { name: "Grey T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_maroon: { name: "Maroon T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_olive: { name: "Olive T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_orange: { name: "Orange T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_purple: { name: "Purple T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_red: { name: "Red T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_salmon: { name: "Salmon T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_tan: { name: "Tan T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_teal: { name: "Teal T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_white: { name: "White T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" },
  undershirt_tshirt_yellow: { name: "Yellow T-Shirt", category: "undershirt", icon: "cosmetic_icons1.png" }
};

const fish: Things = {
  fish_alien_dog: { name: "Unidentified Fish Object", category: "fish", icon: "alien_creature1.png" },
  fish_deep_test: { name: "Axolotl", category: "fish", icon: "creature_main30.png" },
  fish_deep_testb: { name: "Axolotl", category: "fish", icon: "creature_main30.png" },
  fish_deep_testc: { name: "Axolotl", category: "fish", icon: "creature_main30.png" },
  fish_lake_alligator: { name: "Alligator", category: "fish", icon: "creature_main31.png" },
  fish_lake_axolotl: { name: "Axolotl", category: "fish", icon: "creature_main30.png" },
  fish_lake_bass: { name: "Largemouth Bass", category: "fish", icon: "creature_main3.png" },
  fish_lake_bluegill: { name: "Bluegill", category: "fish", icon: "creature_main6.png" },
  fish_lake_bowfin: { name: "Bowfin", category: "fish", icon: "creature_main28.png" },
  fish_lake_bullshark: { name: "Bull Shark", category: "fish", icon: "creature_main33.png" },
  fish_lake_carp: { name: "Carp", category: "fish", icon: "creature_main4.png" },
  fish_lake_catfish: { name: "Catfish", category: "fish", icon: "creature_main9.png" },
  fish_lake_crab: { name: "Crab", category: "fish", icon: "creature_main22.png" },
  fish_lake_crappie: { name: "Crappie", category: "fish", icon: "creature_main19.png" },
  fish_lake_crayfish: { name: "Crayfish", category: "fish", icon: "creature_main13.png" },
  fish_lake_drum: { name: "Drum", category: "fish", icon: "creature_main14.png" },
  fish_lake_frog: { name: "Frog", category: "fish", icon: "creature_main17.png" },
  fish_lake_gar: { name: "Gar", category: "fish", icon: "creature_main29.png" },
  fish_lake_golden_bass: { name: "Golden Bass", category: "fish", icon: "creature_main36.png" },
  fish_lake_goldfish: { name: "Goldfish", category: "fish", icon: "creature_main12.png" },
  fish_lake_guppy: { name: "Guppy", category: "fish", icon: "creature_main15.png" },
  fish_lake_kingsalmon: { name: "King Salmon", category: "fish", icon: "creature_main32.png" },
  fish_lake_koi: { name: "Koi", category: "fish", icon: "creature_main10.png" },
  fish_lake_leech: { name: "Leech", category: "fish", icon: "creature_main24.png" },
  fish_lake_mooneye: { name: "Mooneye", category: "fish", icon: "creature_main35.png" },
  fish_lake_muskellunge: { name: "Muskellunge", category: "fish", icon: "creature_main26.png" },
  fish_lake_perch: { name: "Perch", category: "fish", icon: "creature_main7.png" },
  fish_lake_pike: { name: "Pike", category: "fish", icon: "creature_main23.png" },
  fish_lake_pupfish: { name: "Pupfish", category: "fish", icon: "creature_main34.png" },
  fish_lake_rainbowtrout: { name: "Rainbow Trout", category: "fish", icon: "creature_main2.png" },
  fish_lake_salmon: { name: "Salmon", category: "fish", icon: "creature_main1.png" },
  fish_lake_snail: { name: "Snail", category: "fish", icon: "creature_main18.png" },
  fish_lake_sturgeon: { name: "Sturgeon", category: "fish", icon: "creature_main8.png" },
  fish_lake_toad: { name: "Toad", category: "fish", icon: "creature_main21.png" },
  fish_lake_turtle: { name: "Turtle", category: "fish", icon: "creature_main20.png" },
  fish_lake_walleye: { name: "Walleye", category: "fish", icon: "creature_main5.png" },
  fish_ocean_angelfish: { name: "Angelfish", category: "fish", icon: "creature_main58.png" },
  fish_ocean_atlantic_salmon: { name: "Atlantic Salmon", category: "fish", icon: "creature_main52.png" },
  fish_ocean_bluefish: { name: "Bluefish", category: "fish", icon: "creature_main54.png" },
  fish_ocean_clownfish: { name: "Clownfish", category: "fish", icon: "creature_main57.png" },
  fish_ocean_coalacanth: { name: "Coelacanth", category: "fish", icon: "creature_main70.png" },
  fish_ocean_dogfish: { name: "Dogfish", category: "fish", icon: "creature_main46.png" },
  fish_ocean_eel: { name: "Eel", category: "fish", icon: "creature_main55.png" },
  fish_ocean_flounder: { name: "Flounder", category: "fish", icon: "creature_main47.png" },
  fish_ocean_golden_manta_ray: { name: "Golden Manta Ray", category: "fish", icon: "creature_main76.png" },
  fish_ocean_greatwhiteshark: { name: "Great White Shark", category: "fish", icon: "creature_main71.png" },
  fish_ocean_grouper: { name: "Grouper", category: "fish", icon: "creature_main50.png" },
  fish_ocean_hammerhead_shark: { name: "Hammerhead Shark", category: "fish", icon: "creature_main62.png" },
  fish_ocean_herring: { name: "Herring", category: "fish", icon: "creature_main48.png" },
  fish_ocean_krill: { name: "Krill", category: "fish", icon: "creature_main60.png" },
  fish_ocean_lionfish: { name: "Lionfish", category: "fish", icon: "creature_main64.png" },
  fish_ocean_lobster: { name: "Lobster", category: "fish", icon: "creature_main51.png" },
  fish_ocean_manowar: { name: "Man O' War", category: "fish", icon: "creature_main72.png" },
  fish_ocean_manta_ray: { name: "Manta Ray", category: "fish", icon: "creature_main69.png" },
  fish_ocean_marlin: { name: "Marlin", category: "fish", icon: "creature_main63.png" },
  fish_ocean_octopus: { name: "Octopus", category: "fish", icon: "creature_main65.png" },
  fish_ocean_oyster: { name: "Oyster", category: "fish", icon: "creature_main45.png" },
  fish_ocean_sawfish: { name: "Sawfish", category: "fish", icon: "creature_main56.png" },
  fish_ocean_seahorse: { name: "Seahorse", category: "fish", icon: "creature_main66.png" },
  fish_ocean_sea_turtle: { name: "Sea Turtle", category: "fish", icon: "creature_main73.png" },
  fish_ocean_shrimp: { name: "Shrimp", category: "fish", icon: "creature_main59.png" },
  fish_ocean_squid: { name: "Squid", category: "fish", icon: "creature_main75.png" },
  fish_ocean_stingray: { name: "Sting Ray", category: "fish", icon: "creature_main67.png" },
  fish_ocean_sunfish: { name: "Sunfish", category: "fish", icon: "creature_main49.png" },
  fish_ocean_swordfish: { name: "Swordfish", category: "fish", icon: "creature_main61.png" },
  fish_ocean_tuna: { name: "Tuna", category: "fish", icon: "creature_main53.png" },
  fish_ocean_whale: { name: "Whale", category: "fish", icon: "creature_main74.png" },
  fish_ocean_wolffish: { name: "Wolffish", category: "fish", icon: "creature_main68.png" },
  fish_rain_anomalocaris: { name: "Anomalocaris", category: "fish", icon: "creature_anomalo.png" },
  fish_rain_heliocoprion: { name: "Helicoprion", category: "fish", icon: "creature_main80.png" },
  fish_rain_horseshoe_crab: { name: "Horseshoe Crab", category: "fish", icon: "prehistoric_1.png" },
  fish_rain_leedsichthys: { name: "Leedsichthys", category: "fish", icon: "creature_bigfish.png" },
  mdl_button: { name: "Button", category: "fish", icon: "metal_detect_loot3.png" },
  mdl_casing: { name: "Casing", category: "fish", icon: "metal_detect_loot4.png" },
  mdl_coin: { name: "Old Coin", category: "fish", icon: "metal_detect_loot2.png" },
  mdl_piece_hat: { name: "Hat Fragment", category: "fish", icon: "metal_detect_loot8.png" },
  mdl_piece_monocle: { name: "Monocle Fragment", category: "fish", icon: "metal_detect_loot7.png" },
  mdl_piece_sword: { name: "Blade Fragment", category: "fish", icon: "metal_detect_loot9.png" },
  mdl_piece_watch: { name: "Watch Fragment", category: "fish", icon: "metal_detect_loot6.png" },
  mdl_ring: { name: "Rusted Ring", category: "fish", icon: "metal_detect_loot5.png" },
  mdl_sodatab: { name: "Soda Tab", category: "fish", icon: "metal_detect_loot1.png" },
  luck_moneybag: { name: "Coin Bag", category: "fish", icon: "metal_detect_loot11.png" },
  wtrash_bone: { name: "Bone", category: "fish", icon: "creature_main41.png" },
  wtrash_boot: { name: "Old Boot", category: "fish", icon: "creature_main39.png" },
  wtrash_branch: { name: "Branch", category: "fish", icon: "creature_main44.png" },
  wtrash_diamond: { name: "Diamond", category: "fish", icon: "creature_main40.png" },
  wtrash_drink_rings: { name: "Drink Rings", category: "fish", icon: "creature_main43.png" },
  wtrash_plastic_bag: { name: "Plastic Bag", category: "fish", icon: "creature_main38.png" },
  wtrash_sodacan: { name: "Soda Can", category: "fish", icon: "creature_main37.png" },
  wtrash_weed: { name: "Weed", category: "fish", icon: "creature_main42.png" },
  spectral_femur: { name: "Spectral Femur", category: "fish", icon: "toolicons28.png" },
  spectral_humerus: { name: "Spectral Humerus", category: "fish", icon: "toolicons25.png" },
  spectral_rib: { name: "Spectral Rib", category: "fish", icon: "toolicons26.png" },
  spectral_skull: { name: "Spectral Skull", category: "fish", icon: "toolicons24.png" },
  spectral_spine: { name: "Spectral Spine", category: "fish", icon: "toolicons27.png" }
};

const none: Things = { empty_hand: { name: "EMPTY", category: "none", icon: "toolicons1.png" } };

const tool: Things = {
  net: { name: "bug net", category: "tool", icon: "placeholderitem7.png" },
  painting: { name: "Painting", category: "tool", icon: "toolicons6.png" },
  paint_brush: { name: "Paint Brush", category: "tool", icon: "toolicons5.png" },
  shovel: { name: "SHOVEL", category: "tool", icon: "placeholderitem2.png" },
  chalk_black: { name: "Black Chalk", category: "tool", icon: "toolicons18.png" },
  chalk_blue: { name: "Blue Chalk", category: "tool", icon: "toolicons20.png" },
  chalk_eraser: { name: "Chalk Eraser", category: "tool", icon: "toolicons22.png" },
  chalk_green: { name: "Green Chalk", category: "tool", icon: "toolicons51.png" },
  chalk_red: { name: "Red Chalk", category: "tool", icon: "toolicons19.png" },
  chalk_special: { name: "Special Chalk", category: "tool", icon: "toolicons23.png" },
  chalk_white: { name: "White Chalk", category: "tool", icon: "toolicons17.png" },
  chalk_yellow: { name: "Yellow Chalk", category: "tool", icon: "toolicons21.png" },
  potion_beer: { name: "Hook's Lite", category: "tool", icon: "toolicons10.png" },
  potion_catch: { name: "Catcher's Cola", category: "tool", icon: "toolicons7.png" },
  potion_catch_big: { name: "Catcher's Cola ULTRA", category: "tool", icon: "toolicons8.png" },
  potion_catch_deluxe: { name: "Catcher's Cola DELUXE", category: "tool", icon: "toolicons9.png" },
  potion_grow: { name: "Big Beverage", category: "tool", icon: "toolicons11.png" },
  potion_revert: { name: "Water", category: "tool", icon: "toolicons15.png" },
  potion_small: { name: "Shrink Soda", category: "tool", icon: "toolicons12.png" },
  potion_speed: { name: "Speed Slurpee", category: "tool", icon: "toolicons13.png" },
  potion_speed_burst: { name: "Speed Slurpee XL", category: "tool", icon: "toolicons14.png" },
  potion_wine: { name: "Red Carp-ernet Sauvignon Wine", category: "tool", icon: "toolicons16.png" },
  boxing_glove: { name: "Boxing Glove", category: "tool", icon: "toolicons57.png" },
  boxing_glove_super: { name: "Super Boxing Glove", category: "tool", icon: "toolicons59.png" },
  fishing_rod_collectors: { name: "Collector's Fishing Rod", category: "tool", icon: "toolicons30.png" },
  fishing_rod_collectors_alpha: { name: "Alpha Collector's Fishing Rod", category: "tool", icon: "toolicons35.png" },
  fishing_rod_collectors_glistening: {
    name: "Glistening Collector's Fishing Rod",
    category: "tool",
    icon: "toolicons32.png"
  },
  fishing_rod_collectors_opulent: {
    name: "Opulent Collector's Fishing Rod",
    category: "tool",
    icon: "toolicons33.png"
  },
  fishing_rod_collectors_radiant: {
    name: "Radiant Collector's Fishing Rod",
    category: "tool",
    icon: "toolicons34.png"
  },
  fishing_rod_collectors_shining: {
    name: "Shining Collector's Fishing Rod",
    category: "tool",
    icon: "toolicons31.png"
  },
  fishing_rod_simple: { name: "Simple Fishing Rod", category: "tool", icon: "toolicons29.png" },
  fishing_rod_skeleton: { name: "Spectral Rod", category: "tool", icon: "toolicons36.png" },
  fish_trap: { name: "Freshwater Fishing Buddy", category: "tool", icon: "toolicons37.png" },
  fish_trap_ocean: { name: "Saltwater Fishing Buddy", category: "tool", icon: "toolicons38.png" },
  guitar: { name: "Guitar", category: "tool", icon: "toolicons46.png" },
  guitar_black: { name: "Black Guitar", category: "tool", icon: "toolicons49.png" },
  guitar_gold: { name: "Golden Guitar", category: "tool", icon: "toolicons53.png" },
  guitar_gradient: { name: "Fade Guitar", category: "tool", icon: "toolicons47.png" },
  guitar_pink: { name: "Pink Guitar", category: "tool", icon: "toolicons50.png" },
  guitar_stickers: { name: "Stickered Guitar", category: "tool", icon: "toolicons48.png" },
  metal_detector: { name: "Metal Detector", category: "tool", icon: "toolicons39.png" },
  ringbox: { name: "Ring Box", category: "tool", icon: "toolicons56.png" },
  scratch_off: { name: "Scratch Off", category: "tool", icon: "toolicons52.png" },
  scratch_off_2: { name: "Scratch Off", category: "tool", icon: "toolicons54.png" },
  scratch_off_3: { name: "Scratch Off", category: "tool", icon: "toolicons55.png" },
  tambourine: { name: "Tambourine", category: "tool", icon: "toolicons58.png" },
  treasure_chest: { name: "Treasure Chest", category: "tool", icon: "toolicons4.png" }
};

const furniture: Things = {
  prop_beer: { name: "6-Pack Prop", category: "furniture", icon: "cosmetic_icons59.png" },
  prop_boombox: { name: "Royalty Free Boombox Prop", category: "furniture", icon: "cosmetic_icons49.png" },
  prop_bush: { name: "Bush Prop", category: "furniture", icon: "cosmetic_icons52.png" },
  prop_campfire: { name: "Campfire Prop", category: "furniture", icon: "cosmetic_icons53.png" },
  prop_canvas: { name: "Canvas Prop", category: "furniture", icon: "cyube.png" },
  prop_chair: { name: "Chair Prop", category: "furniture", icon: "cosmetic_icons54.png" },
  prop_greenscreen: { name: "Green Screen Prop", category: "furniture", icon: "cosmetic_icons67.png" },
  prop_island_big: { name: "Large Island Entrance", category: "furniture", icon: "toolicons45.png" },
  prop_island_med: { name: "Medium Island Entrance", category: "furniture", icon: "toolicons44.png" },
  prop_island_tiny: { name: "Tiny Island Entrance", category: "furniture", icon: "toolicons43.png" },
  prop_picnic: { name: "Picnic Blanket Prop", category: "furniture", icon: "cosmetic_icons50.png" },
  prop_rock: { name: "Rock Prop", category: "furniture", icon: "cosmetic_icons51.png" },
  prop_table: { name: "Table Prop", category: "furniture", icon: "cosmetic_icons55.png" },
  prop_test: { name: "prop test", category: "furniture", icon: "cyube.png" },
  prop_therapy_seat: { name: "Therapy Seat Prop", category: "furniture", icon: "cosmetic_icons56.png" },
  prop_toilet: { name: "Toilet Prop", category: "furniture", icon: "cosmetic_icons58.png" },
  prop_well: { name: "Well Prop", category: "furniture", icon: "cosmetic_icons60.png" },
  prop_whoopie: { name: "Fart Balloon Prop", category: "furniture", icon: "cosmetic_icons57.png" }
};

export const items: Things = {
  ...fish,
  ...none,
  ...tool,
  ...furniture
};

export const cosmetics: Things = {
  ...species,
  ...accessory,
  ...bobber,
  ...eye,
  ...hat,
  ...legs,
  ...mouth,
  ...nose,
  ...overshirt,
  ...pattern,
  ...primary_color,
  ...secondary_color,
  ...tail,
  ...title,
  ...undershirt
};

const all = { ...items, ...cosmetics };
export default all;
